baseURL = 'https://coderkeung.cn/'
languageCode = 'zh-cn'
title = "人间游荡"
theme = 'hugo-paper'

[params]
author = 'CoderKeung'
notoFont = true
captionPrefix = '◎'
enableCaption = true
homeDirection = "游荡人间"
homeDirectionSub = "人生就是自己的往事和他人的序章"
postURL = "/posts/"
postURLName = "博客"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = 'manni'
    tabWidth = 4
